//! Mobile `ComponentTable` (#44): the kanji component table (KRADFILE) — the
//! visual bridge between what the recogniser *saw* at an unemittable glyph
//! and what a dictionary can *offer* for it.
//!
//! At the `呟` gap the head's top-5 is `咳 咬 啦 哮 眩` — all 口/亠 characters —
//! while `呟` itself decomposes to `亠 口 幺 玄`. Sharing components is what
//! selects the right candidate. The table therefore carries both directions:
//! [`ComponentTable::components_of`] (generation / filtering) and
//! [`ComponentTable::kanji_with`] (a precomputed posting list, never a scan
//! of the whole table per call), plus [`ComponentTable::idf_of`] so sharing
//! `車` can be weighed against sharing `一`.
//!
//! The asset `assets/components/krad_components.txt` is a merged, vendored
//! copy of EDRDG **KRADFILE** and **KRADFILE2** (see the `PROVENANCE.txt`
//! beside it; generated by mobile's `tools/build_component_table.py` and
//! never hand-edited). [`ComponentTable::load`] reads it; `None` on a
//! missing or empty file degrades callers to the head-only list.

use std::collections::HashMap;

pub struct ComponentTable {
    /// kanji -> its components, in the asset's order.
    components: HashMap<char, Vec<char>>,
    /// component -> every kanji carrying it, ascending by codepoint.
    inverted: HashMap<char, Vec<char>>,
    /// component -> inverse document frequency over the kanji in this table.
    idf: HashMap<char, f32>,
    entry_count: usize,
    // Mobile API surface, pinned by tests (the index population the IDF is
    // computed over); no production reader yet.
    #[allow(dead_code)]
    kanji_count: usize,
}

impl ComponentTable {
    /// Parse the table from its text form. Pure — no I/O — so unit tests
    /// exercise the same code the binary runs.
    ///
    /// Tolerant by design: a line without a single-character key or with no
    /// parseable component is skipped rather than failing, because this
    /// parses a shipped asset. The unit test pinning the entry count (12,156)
    /// is what makes a corrupted asset fail loudly. The **first** entry for a
    /// key wins, mirroring the generator's `setdefault`; components are
    /// de-duplicated within a line.
    pub fn parse(text: &str) -> Self {
        let mut table: HashMap<char, Vec<char>> = HashMap::new();
        for line in text.lines() {
            // Key is exactly one character; a blank or comment line has no
            // colon right after the first character, so this also skips
            // anything malformed at the front.
            let mut chars = line.chars();
            let Some(key) = chars.next() else { continue };
            let Some(rest) = chars.as_str().strip_prefix(':') else {
                continue;
            };
            if table.contains_key(&key) {
                continue;
            }
            let mut comps: Vec<char> = Vec::new();
            for token in rest.split(' ') {
                if token.chars().count() == 1 {
                    let c = token.chars().next().expect("single-char token");
                    if !comps.contains(&c) {
                        comps.push(c);
                    }
                }
            }
            if !comps.is_empty() {
                table.insert(key, comps);
            }
        }

        // The IDF universe is the kanji subset, mirroring `odp.kanji` in the
        // measurement probe: a stray non-ideograph key must not shift every
        // weight.
        let kanji_count = table.keys().filter(|c| is_kanji(**c)).count();
        let mut posting: HashMap<char, Vec<char>> = HashMap::new();
        for (kanji, comps) in &table {
            if !is_kanji(*kanji) {
                continue;
            }
            for c in comps {
                posting.entry(*c).or_default().push(*kanji);
            }
        }
        // Posting lists are sorted once here (the asset already is) so that
        // `kanji_with` returns codepoint order without re-sorting.
        let mut inverted: HashMap<char, Vec<char>> = HashMap::with_capacity(posting.len());
        let mut idf: HashMap<char, f32> = HashMap::with_capacity(posting.len());
        for (c, mut carriers) in posting {
            carriers.sort();
            if kanji_count > 0 {
                idf.insert(c, ((kanji_count as f64) / (carriers.len() as f64)).ln() as f32);
            }
            inverted.insert(c, carriers);
        }

        let entry_count = table.len();
        Self {
            components: table,
            inverted,
            idf,
            entry_count,
            kanji_count,
        }
    }

    /// Load the shipped table; `None` when the file is missing, unreadable or
    /// parses to nothing (callers then keep the head-only list).
    pub fn load(path: &std::path::Path) -> Option<Self> {
        let text = std::fs::read_to_string(path).ok()?;
        let table = Self::parse(&text);
        if table.entry_count == 0 {
            return None;
        }
        Some(table)
    }

    /// Number of entries parsed — every key in the asset.
    pub fn entry_count(&self) -> usize {
        self.entry_count
    }

    /// Number of kanji in the table — the population the IDF is computed
    /// over, so a stray non-ideograph key cannot shift every weight.
    /// (Mobile API surface, pinned by tests; no production reader yet.)
    #[allow(dead_code)]
    pub fn kanji_count(&self) -> usize {
        self.kanji_count
    }

    /// The components of `ch`, or an empty list for a character the table has
    /// no entry for. Never fails: an unknown character is simply no evidence.
    pub fn components_of(&self, ch: char) -> &[char] {
        self.components.get(&ch).map(Vec::as_slice).unwrap_or(&[])
    }

    /// Whether the table has an entry for `ch`.
    /// (Mobile API surface, pinned by tests; no production reader yet.)
    #[allow(dead_code)]
    pub fn has_components(&self, ch: char) -> bool {
        self.components.contains_key(&ch)
    }

    /// Every kanji carrying **all** of `all` — the strict component filter.
    /// Backed by the precomputed inverted index: the smallest posting list
    /// among the requested components is filtered by the remaining ones.
    ///
    /// An **empty requirement returns nothing** (no evidence is not a licence
    /// to return all 12,156 kanji), and a component **no kanji carries**
    /// yields an empty result rather than being ignored. Result is ascending
    /// by codepoint and free of duplicates; repeating a component does not
    /// change the result.
    pub fn kanji_with(&self, all: &[char]) -> Vec<char> {
        if all.is_empty() {
            return Vec::new();
        }
        let mut smallest: Option<&Vec<char>> = None;
        for c in all {
            let Some(posting) = self.inverted.get(c) else {
                return Vec::new();
            };
            if posting.is_empty() {
                return Vec::new();
            }
            if smallest.is_none_or(|s: &Vec<char>| posting.len() < s.len()) {
                smallest = Some(posting);
            }
        }
        let candidates = match smallest {
            Some(c) => c,
            None => return Vec::new(),
        };
        let mut out: Vec<char> = Vec::new();
        'next: for k in candidates {
            let Some(comps) = self.components.get(k) else {
                continue;
            };
            for need in all {
                if !comps.contains(need) {
                    continue 'next;
                }
            }
            out.push(*k);
        }
        out
    }

    /// `ln(kanji_count / kanji_count_containing(component))` — nats, not
    /// bits. An unknown component returns `0.0`: it adds no weight and can
    /// never make a fraction NaN.
    pub fn idf_of(&self, component: char) -> f32 {
        self.idf.get(&component).copied().unwrap_or(0.0)
    }
}

/// CJK ideograph ranges, mirroring `odp.kanji` in the measurement probe.
fn is_kanji(c: char) -> bool {
    let o = c as u32;
    (0x3400..=0x4DBF).contains(&o) || (0x4E00..=0x9FFF).contains(&o) || (0xF900..=0xFAFF).contains(&o)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real asset, read from disk (mirrors mobile `ComponentTableTest`).
    fn asset_text() -> Option<String> {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/components/krad_components.txt");
        std::fs::read_to_string(&path).ok()
    }

    #[test]
    fn components_of_fukan_are_exactly_the_measured_set() {
        let Some(text) = asset_text() else {
            eprintln!("skipping: components asset not present");
            return;
        };
        let table = ComponentTable::parse(&text);
        let mut got = table.components_of('呟').to_vec();
        got.sort();
        assert_eq!(got, vec!['亠', '口', '幺', '玄']);
        assert_eq!(table.components_of('呟').len(), 4);
    }

    #[test]
    fn kanji_with_uses_the_inverted_index_and_requires_every_component() {
        let Some(text) = asset_text() else {
            eprintln!("skipping: components asset not present");
            return;
        };
        let table = ComponentTable::parse(&text);
        let both = table.kanji_with(&['口', '亠']);
        assert!(both.contains(&'呟'), "呟 carries both 口 and 亠");
        assert!(
            (2..table.kanji_count()).contains(&both.len()),
            "the pair is selective, not vacuous: {}",
            both.len()
        );
        for k in &both {
            let comps = table.components_of(*k);
            assert!(
                comps.contains(&'口') && comps.contains(&'亠'),
                "{k} returned for 口+亠 but does not carry both"
            );
        }
        let mut sorted = both.clone();
        sorted.sort();
        assert_eq!(both, sorted, "codepoint order, deterministic");
        assert_eq!(both, table.kanji_with(&['口', '亠', '口']), "repeats change nothing");
        assert!(table.kanji_with(&[]).is_empty(), "no evidence -> nothing");
        assert!(
            table.kanji_with(&['口', '\u{E000}']).is_empty(),
            "unknown component -> nothing"
        );
    }

    #[test]
    fn idf_weighs_a_rare_component_above_a_common_one() {
        let Some(text) = asset_text() else {
            eprintln!("skipping: components asset not present");
            return;
        };
        let table = ComponentTable::parse(&text);
        assert!(table.idf_of('車') > table.idf_of('一'));
        assert!(table.idf_of('一') > 0.0);
        assert_eq!(table.idf_of('\u{E000}'), 0.0, "unknown: no weight, never NaN");
    }

    #[test]
    fn unknown_characters_are_empty_rather_than_exceptional() {
        let table = ComponentTable::parse("一:一\n");
        assert!(!table.has_components('\u{E000}'));
        assert!(table.components_of('\u{E000}').is_empty());
        assert!(table.components_of('あ').is_empty());
    }

    #[test]
    fn parse_dedupes_repeated_components_and_keeps_the_first_entry() {
        let parsed = ComponentTable::parse(
            &[
                "一:一 一", // repeated component: deduped
                "丁:一 亅",
                "not a table line",
                " :口", // non-kanji key: kept in the table, excluded from the index
                "ニ:一 二", // katakana key: same
                "一:口 亅", // duplicate key: the generator's setdefault keeps the first
            ]
            .join("\n"),
        );
        assert_eq!(parsed.components_of('一'), &['一']);
        assert_eq!(parsed.components_of('丁'), &['一', '亅']);
        assert_eq!(parsed.components_of(' '), &['口']);
        assert_eq!(parsed.entry_count(), 4);
        assert_eq!(parsed.kanji_count(), 2);
        assert_eq!(parsed.kanji_with(&['一']), vec!['一', '丁']);
        assert!(parsed.kanji_with(&['口']).is_empty());
        // ln(2 kanji / 1 carrier) for 亅; ln(2/2) = 0 for the ubiquitous 一.
        assert!((parsed.idf_of('亅') - 0.6931472).abs() < 1e-5);
        assert!((parsed.idf_of('一') - 0.0).abs() < 1e-6);
    }

    #[test]
    fn the_bundled_asset_still_has_12156_entries() {
        let path =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("assets/components/krad_components.txt");
        let Ok(text) = std::fs::read_to_string(&path) else {
            eprintln!("skipping: {} not present", path.display());
            return;
        };
        let lines: Vec<&str> = text.lines().collect();
        // PROVENANCE.txt pins the entry count; a truncated or regenerated
        // asset must fail loudly here, not silently degrade every candidate
        // set downstream.
        assert_eq!(12156, lines.len(), "entry count in components/krad_components.txt");
        for (i, line) in lines.iter().enumerate() {
            let mut chars = line.chars();
            let second = chars.nth(1);
            assert!(
                line.len() >= 3 && second == Some(':') && !chars.as_str().starts_with(' '),
                "line {} is not 'kanji:components': {}",
                i + 1,
                line.chars().take(40).collect::<String>()
            );
        }
        // Every line must survive parsing — a line the parser skips would
        // shrink the table below the line count above.
        let table = ComponentTable::parse(&text);
        assert_eq!(12156, table.entry_count());
        assert_eq!(12156, table.kanji_count());
        assert_eq!("一:一", lines[0], "first line of the codepoint-sorted asset");
    }

    #[test]
    fn load_rejects_a_missing_or_empty_asset() {
        assert!(
            ComponentTable::load(std::path::Path::new("/nonexistent/krad_components.txt")).is_none()
        );
        let dir = std::env::temp_dir();
        let empty = dir.join("instantjpdict_empty_components.txt");
        std::fs::write(&empty, "").expect("write fixture");
        assert!(ComponentTable::load(&empty).is_none(), "empty parses to nothing");
        let _ = std::fs::remove_file(&empty);
    }
}
